apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argo-cd
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.92.4
    helm:
      releaseName: tailscale-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
