apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "11.3.6"
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/hostname: grafana
      hosts: [grafana]
      tls:
        - hosts: [grafana]
    grafana.ini:
      server:
        root_url: https://grafana.pipefish-manta.ts.net
      auth.basic:
        enabled: true
    sidecar:
      dashboards:
        enabled: true
        env:
          HEALTHCHECK_PORT: "9004"
      datasources:
        enabled: true
