apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  releaseName: kube-prometheus-chart
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: prometheus
    grafana:
      enabled: true
      plugins:
        - cloudflare-app
      initChownData:
        enabled: false
      persistence:
        enabled: true
        size: 10Gi
      service:
        type: ClusterIP
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: tailscale
        annotations:
          tailscale.com/hostname: grafana
        hosts: [grafana]
        tls:
          - hosts: [grafana]
      grafana.ini:
        server:
          root_url: https://grafana.pipefish-manta.ts.net
      resources:
        requests:
          cpu: 20m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    prometheus:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: tailscale
        annotations:
          tailscale.com/hostname: prometheus
        hosts: [prometheus]
        tls:
          - hosts: [prometheus]
      prometheusSpec:
        retention: 15d
        serviceMonitorSelectorNilUsesHelmValues: false
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: [ReadWriteOnce]
              resources:
                requests:
                  storage: 50Gi
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: tailscale
        annotations:
          tailscale.com/hostname: alertmanager
        hosts: [alertmanager]
        tls:
          - hosts: [alertmanager]
