apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    prometheus-node-exporter:
      prometheus:
        monitor:
          relabelings:
            # Rename job to "node" for compatibility with Node Exporter Full dashboard (ID 1860)
            - targetLabel: job
              replacement: node
