apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - loki-datasource.yaml
  - alloy.yaml
  - networkpolicy.yaml
