apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - loki-datasource.yaml
  - prometheus-datasource.yaml
  - alloy.yaml
  - networkpolicy.yaml
  - dashboards/node-exporter.yaml
  - dashboards/flux-cluster.yaml
  - dashboards/flux-control-plane.yaml
  - dashboards/flux-logs.yaml
  - flux-podmonitor.yaml
