apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: default
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: 30s
