apiVersion: ENC[AES256_GCM,data:Eio=,iv:lNCS2IJgyYu2+A163gBsvXD3SrFJvluwKYquRleDsBk=,tag:H6OD4vVRUezGtBfQAlQIsg==,type:str]
kind: ENC[AES256_GCM,data:T3JuJhLc,iv:XHeFuAa+hUGTlU0S9kDK2zSOKNdVh08Zw5xtVOA49V8=,tag:g/rDYgmK67hIbgHQ4dyVew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xN+eudJqinHviq+ULg==,iv:eTj/k2k/U6BaQ7v3+vKmSzpspUcmNDq4X9clMuFaSr8=,tag:aXqrvfMf+fltcTPWE6Fbmg==,type:str]
    namespace: ENC[AES256_GCM,data:k9q/4i7nug==,iv:vgj5hYh3dKsjxGjy/I8xqzX44SxKBQpQXwElejaimjE=,tag:Twu8AZ3+SuKcBGem4TFgYg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:6nqrfFA=,iv:BJ/AuEZE2zOzzHwLTzk8UedloSiuINNlHMd5iOc/zmA=,tag:7B8wQ13lKXvmyOzJT6RbHA==,type:str]
    admin-password: ENC[AES256_GCM,data:kXQDX/dhROMT+nISdXIjNa22BNnZfUPd,iv:TvMUBhK3RAJ6fZpa8GN6aEliGGlUqsl/HiMUZzSWWDA=,tag:9y3Y+SGyutOZ4d2H70k+JQ==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISWVSVmpGM1h2VzJyTEw0
            dHNTdUp2VHc0aFVpRXdQS1VHaEhCbmM5RTNrCjF1eEIxbnRKdFlkMXVtdEpJYmht
            YTNpNWU2b0VUK0VVYS84K2o5UUdDbEEKLS0tIHVvK2hGT1ZHNzNIeHowYzB6VHRi
            cC8wMENaSFFMeHZmWmtabUNNM0FxRGcKhlyeFuInDujQX+CWhTF87j4fyE3QEonN
            EU7Ltwj7vPOTxUyW9t62pKB90arayM7SstNowI4AcXMQEZU2JVgCVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:56:19Z"
    mac: ENC[AES256_GCM,data:g1dSF0yieUjc9onmh4YdNVJsP7KnXJlyoEw03+wzRSawu3e+82j9Ng5VOGqbuKgOXHG2xro9hMQwYUAhfkD7RWYrwDKYTsgEz0/LpzYU2PNu27+U+qqucVTPCPjApcvUY2D+9wMaukDOh4POsBwiKSW2gG+WMIp5kabFA2dRqMM=,iv:B2kUy8lGDj9cMD+RtT4ZV7vR9iEckS2utGTvmSyTqyk=,tag:TH3kFTdHxFw2GNWKLXv5Iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
