apiVersion: ENC[AES256_GCM,data:XeQ=,iv:Fa83K/o/QNhkAbeI74QavjqAqTTyFEHnDuyBBOTTYhc=,tag:mZxF4NPaS2NR8VS0fscrJw==,type:str]
kind: ENC[AES256_GCM,data:nfsWtpzY,iv:mAeyA8xlBqrEhbyqd6kZ5ZT9WfFVTDuZ/4elGaLmkwM=,tag:ahbgqAj0imTL8i4+8UhzEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JYTePyyTPHi5aBESe1OyCNh3Qx0=,iv:w0RFskIU+QqAu9BSec2EZPjbjMVi9op6GHuWh7wY0A0=,tag:VqWiJOGUIBVxu72v71Gkog==,type:str]
    namespace: ENC[AES256_GCM,data:f1Fj0V98Aw==,iv:1gW2aVmUDSiVgbi/uLEmG6vlQLvqobHf43pYJ+1VznU=,tag:UnRjDqCRY+OkQZPeSaSj7w==,type:str]
type: ENC[AES256_GCM,data:aXx9cR+M,iv:Tj1n1LUx0owZJGbf/N+E1EzQMwLBlSHe8aKhFpxXrmA=,tag:ZelF7GGo5Br5GbmFpGJ27Q==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:5oHkRhM=,iv:MbRgD6WMtXLqhbgD+5KZvpBEMX4XL22fv8OzXJ866rY=,tag:V3TPWkgV7/QV4te0MWofhg==,type:str]
    admin-password: ENC[AES256_GCM,data:DC1VuZ3SY1bqWg==,iv:ltxSZM49ZbTlbS2uGqFFtdS0Z5kdDtyHUO5JgLWFqAk=,tag:N4aC4gUM4U5tAvA1DGlYAA==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNnhEcmZIZUxEUkp0VDVh
            eEpWc2I1bFNzeG9TV3J0Qk0vR1JXUWY3L1VVCkliZENYSktZemJnVzVmRzhHMG9G
            bDdmKzFMdVJ4d0tlYWxFWEs0aENVZm8KLS0tIEdoOE5jbUtmTjdlZ0V4UklLeCth
            VzliQUJBaStOTDY3Rnd6ZlNwaXlQZXcKMB+0uoyH81r/ZHGCB/1S8kPlfb+FGc2P
            7d9RM+9UeYrV+m9/+p0aWauYJGkowSwPsCZAkEFin1KzyARWU0r0qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T23:12:52Z"
    mac: ENC[AES256_GCM,data:15QFGk0pW4nQEOoFsouA/bd33DNgvG+/fU0zNPP5iAFgt4hkKPZxaWPs1/Kw62AxIVXrd8J8EzGEdz3ZrwqI5BntOTYbM31D4RXSix3VxkRMXRd6sMGZegVOYTAksK24rAkYbARJyN/GB73soo6JfKPmyc5atTs0Kasgi43tVgI=,iv:drU0TG7RwDfPloP+7qAkA/T2I0XkMWEiKRURJMRlZR4=,tag:+yMiWRqxER/JQiLZnAkA9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
