apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashdot
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: dashdot
      sourceRef:
        kind: HelmRepository
        name: oben01
        namespace: flux-system
  values:
    podAnnotations: {}
    securityContext:
      privileged: true
    service:
      type: ClusterIP
      port: 3001
    extraVolumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
    extraVolumeMounts:
      - name: host-proc
        mountPath: /proc
        readOnly: true
      - name: host-sys
        mountPath: /sys
        readOnly: true
    config:
      show_host: true
      widget_list:
        - os
        - cpu
        - storage
        - ram
        - network
    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits: { cpu: 200m, memory: 256Mi }
