apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashdot
  namespace: default
  annotations:
    tailscale.com/hostname: dashdot
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: dashdot
      port:
        number: 3001
  tls:
    - hosts: [dashdot]
