# Source - https://stackoverflow.com/a
# Posted by Yan QiDong, modified by community. See post 'Timeline' for change history
# Retrieved 2025-12-29, License - CC BY-SA 4.0

kind: PersistentVolume
apiVersion: v1
metadata:
  name: foundry-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 50Gi
  local:
    path: /home/jack/foundrydata
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - new-bermuda
