apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: foundry
  name: foundry
  namespace: default
spec:
  ports:
    - name: "foundry-port"
      port: 30000
      targetPort: 30000
  selector:
    io.kompose.service: foundry
