apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: foundry-claim0
  name: foundry-claim0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gb
