apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: foundry
  name: foundry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: foundry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: foundry
    spec:
      volumes:
        - name: foundry-pv-storage
          persistentVolumeClaim:
            claimName: foundry-claim
      containers:
        - name: foundry-container
          hostname: foundry
          volumeMounts:
            - mountPath: "/data"
              name: foundry-pv-storage
          image: felddy/foundryvtt:13
          ports:
            - containerPort: 30000
              protocol: TCP
          env:
              - name: FOUNDRY_ADMIN_KEY
                valueFrom:
                  secretKeyRef:
                    name: foundry-creds
                    key: admin-pw
              - name: FOUNDRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: foundry-creds
                    key: password
              - name: FOUNDRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: foundry-creds
                    key: username
