# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-claim
  namespace: default
spec:
  storageClass: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
