apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _sources/ks.yaml
  - tailscale/ks.yaml
  - foundry/ks.yaml
  - monitoring/ks.yaml
  - paperless/ks.yaml
  - satisfactory/ks.yaml
  - homepage/ks.yaml
  - dashdot/ks.yaml
  - donetick/ks.yaml
  - portainer/ks.yaml
