apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: foundry
    spec:
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            claimName: foundry-data-claim
      containers:
        - name: foundry
          image: felddy/foundryvtt:release
          ports:
            - containerPort: 30000
          env:
            - name: FOUNDRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: foundry-secret
                  key: username
            - name: FOUNDRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foundry-secret
                  key: password
          volumeMounts:
            - name: foundry-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
