apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data
  labels:
    app: foundry
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  hostPath:
    path: /home/jack/foundrydata
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [new-bermuda]
