apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  selector:
    matchLabels:
      app: foundry
  resources:
    requests:
      storage: 50Gi
