apiVersion: ENC[AES256_GCM,data:RYE=,iv:y7nFS/w1QKkku9mjYIlzP2QMIgBO8nZVWgzGZW0GAyQ=,tag:ZDgp+xhsY8iku8+3lts7BA==,type:str]
kind: ENC[AES256_GCM,data:JlT0ovHX,iv:GnjAQZjUqcuZoCk6fd/zfxXkQ5LGuKQweMYBTQstHyY=,tag:UGJfTQphKM6jMdtKpDcSRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WxJqJ5gDDtI+BGizsqY=,iv:X2Q70+0TcpqNokNeNhBZ64i2p4XGhOdK9B8TZ4o5xxo=,tag:Gh0w1bVgo4POZj0HYOMb0g==,type:str]
    namespace: ENC[AES256_GCM,data:aQQjBgvw3w==,iv:Lasmy8wLtOPr4WSQLcHX4e9wmpZdexRynYPpPG2oHe8=,tag:qOpASr3pp7CXtDsp0N9PEA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:OeWsAeZk7uCP,iv:aUnZCUGXeZsQ3b9VPuhx0yeO1BwAORcwbIVrSK5RNnk=,tag:FfdqBz1eDVPk9aOM9CyqWg==,type:str]
    password: ENC[AES256_GCM,data:dSvXW2ttGVvI,iv:/dIw0TqxNzWw1bBIQUKYDK+Nbgii7I823OZDqYLtV6I=,tag:ZPv2pWLcv27TvU055zCRvw==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYWFka290bGdhZi9sblpL
            UDdiZDI0K2t1dVhMbGVSKy9EWnUxSWhGVld3CkV6QS90d25ISXp1dVNsMEI5a3pN
            RC9wVDIyRVJLSHNHUFNFSXF2WTlrNjQKLS0tIEJPOHlQdWRsVzRHZ3JZazRPL3NQ
            Y3ZIQjRpRC95Vjg2Y0RXWm01aURKd3cKQ4Zv9DdBdCfHUQzJ8J4VCCRN8fi4kXy7
            vcUZwtXGVh9kqYgojG+SZsBqyDNzgTmK/ODh9frc7AqcykgFWFJ+tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:56:19Z"
    mac: ENC[AES256_GCM,data:d1ALU1JUoW4oj7LeWF7qJ1KV1cmBH013g+I/AaTZp9+RHn9l5RFGeAPh48xaj0qD9sEHO9H+qxf9Rznby4tDkVJV6O1V6kCJFQnJmG+YvPzKVZOwsmHzPJM6QkqU5Xdrw73iKCoWTBCLsQhP2GzlV6QiZqZDmt6eDBKE+Soh4o0=,iv:l6SDyhEPLj88R5DyGpgig77hTMg1YfyRio0QUJBiXNU=,tag:/J5XStqs18F7hRVVgtZhvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
