apiVersion: v1
kind: PersistentVolume
metadata:
  name: donetick-data
  labels: { app: donetick }
spec:
  storageClassName: manual
  capacity: { storage: 10Gi }
  hostPath: { path: /home/jack/donetick/data }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
