apiVersion: ENC[AES256_GCM,data:Zco=,iv:hCbJB8C9uGuzpnfOBn3+CTuCgRNUczYi0qKgP6TMV+o=,tag:CKZcgjh8QFX4BFapM1l2jQ==,type:str]
kind: ENC[AES256_GCM,data:mYGjuZBC,iv:ZUuGyX6MJnkpUnL9/SySECWrBUKraPCpJ8pg1CcksM0=,tag:f5Hwpgwzf3yYcICTAsTR0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cetsFMHz1DcR7psxdR6v,iv:O23T5tzCm+5ogd76xREaeSVVwIJZoInUDSvzpPyV4fc=,tag:RLA76QubVYpZe3+B22lDGQ==,type:str]
    namespace: ENC[AES256_GCM,data:zqlnUjbByA==,iv:BWoV2hT4+BOXY39O8ugARSvSehk/iUsuCcF5L484cAw=,tag:HbxwQsY4d3qi+6MBVqvShQ==,type:str]
stringData:
    jwtSecret: ENC[AES256_GCM,data:wKIXzCkPzHCcF1AC0fAJbF1UmUyp4Ek6jHVdLJduAF33rZelgOLQh8ihIbU=,iv:HsOX6EYkle2tw5EK66cLgbqzcsbYUxXQUraAySONdAU=,tag:MYllh2gYq2jd3vXuKJFCpQ==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1Y4R0h2Mmdabkc5TE1z
            Z2d2QzU5cjB3WjA2TGo0UTJLbjNPeHJSRTNRCmZCMHk5YVB6bGU4L2lNc0dzR1ph
            NndUSTM2WTNhRjk3UStwbGpkcXVZOTgKLS0tIE1iTXM1ekdDSDM5cDY0TU5nNXF3
            V2RHa1ZsQ3NBMUhsNThvTUVsbng2Q28KYqqlSKXCg2xYfNhX2/X5ZuiWEAqjEf9+
            G273bXFtVOa3cK2PXGxdYXfHDM+HeX+yGi0ZXoKk+N7peQfanMhILg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:56:19Z"
    mac: ENC[AES256_GCM,data:82MFcQoUT+Jed7ONDIj033KCNiOtdSe6BtcoxfAZLyGQtkBXHFuJpXtpLz+/jm5DcLlT8sS1nP7DfiFGmI4sU+nJM6pQXyXRjEXGgYqmFV/ztX75xBe6gl4T+Kv+zlZlPhSImLrZmNG4DMaQvNRb4JRA959wNWV0h2b+tQDqbHo=,iv:4opOcl69AiToMDiEveSTa50hWZFIdecFQsfQ9SkgEBY=,tag:7AUQ8BxctW+wUrNxJpSW6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
