apiVersion: v1
data:
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_TIME_ZONE: America/New_York
  PAPERLESS_URL: https://paperless.weakphi.sh
  USERMAP_GID: "1000"
  USERMAP_UID: "1000"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: webserver-docker-compose-env
  name: docker-compose-env
