apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer
  namespace: portainer
  annotations:
    tailscale.com/hostname: portainer
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: portainer
      port:
        number: 9000
  tls:
    - hosts: [portainer]
