apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data-claim
  namespace: portainer
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  selector: { matchLabels: { app: portainer, volume: data } }
  resources: { requests: { storage: 10Gi } }
