apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvcs.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - web.yaml
  - worker.yaml
  - scheduler.yaml
  - services.yaml
  - ingress.yaml
