apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-data
  labels: { app: paperless, volume: data }
spec:
  storageClassName: manual
  capacity: { storage: 10Gi }
  hostPath: { path: /home/jack/paperless/data }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
  labels: { app: paperless, volume: media }
spec:
  storageClassName: manual
  capacity: { storage: 50Gi }
  hostPath: { path: /home/jack/paperless/media }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume
  labels: { app: paperless, volume: consume }
spec:
  storageClassName: manual
  capacity: { storage: 10Gi }
  hostPath: { path: /home/jack/paperless/consume }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-postgres
  labels: { app: paperless, volume: postgres }
spec:
  storageClassName: manual
  capacity: { storage: 10Gi }
  hostPath: { path: /home/jack/paperless/postgres }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-redis
  labels: { app: paperless, volume: redis }
spec:
  storageClassName: manual
  capacity: { storage: 1Gi }
  hostPath: { path: /home/jack/paperless/redis }
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ReadWriteOnce]
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [new-bermuda] }
