apiVersion: ENC[AES256_GCM,data:mt8=,iv:ZpM53SSC67njeik2gdbrREUfZJOxKD+vgKe2AOlEJqQ=,tag:x1f/7NvL27x/kN6GVeCUXg==,type:str]
kind: ENC[AES256_GCM,data:WnYMA0j3,iv:H4sJ5jZ0JURVLjwFBEgBtosVxyPBDGRnYB6Fkju/j1o=,tag:g8DW9lT6AVMcbc9cRsir9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jk6RLGLKYeIBLpaA9xaixg==,iv:HS0CUgJnn6bDE3o+0kT7H+CkRs60OisE/yH81dsqsjM=,tag:1P4wtn3SaN6sG78RiyXKJQ==,type:str]
    namespace: ENC[AES256_GCM,data:205fZgxXKg==,iv:2hEI1zD23DaNnKcrDUs7XS99k5DT6dLECFEK/I+nlMM=,tag:t5VbqbFXymgcEO27fabvFQ==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:SZNC8AKF2RzDotvcjY+4HvEhD4U3UrgZK8MW4PnFnDc=,iv:np+5tA+dq30Ep+dIBiz8wAWrjJmniqjjwqHWVzilE9g=,tag:N8PbJapKUDRoRL7ZEkaC0Q==,type:str]
    secretKey: ENC[AES256_GCM,data:CZAA9e0mh+MVkW8LSzecLaL0hYErvMZ8W5YDfUeVCSgVt58bMtw+IuCRf6pcZHdk56J5l4hCxSCurYiEKSSJcQ==,iv:KCSFthTP9pHPfctc9sxh9XILTx1h8bd+ZZfDxiOBkII=,tag:hQP6mpLyVP8LmRsqobOg/Q==,type:str]
    adminUser: ENC[AES256_GCM,data:McjGfsI=,iv:jImh8D5QjPZ5KZTW6PZFfwmMlKqpjxxa59hMUXAgxU4=,tag:3fNNWabMPNUxig4/0XcS7w==,type:str]
    adminPassword: ENC[AES256_GCM,data:ZsqMv4bngbeDRd3xR15FAA16eUE6jMMJ5KW5JRYGCBU=,iv:hqZ5KvqAZxvcl5N4nHaJS1iV4WnjaWjM9p3jRqlEVWQ=,tag:bR/ehPhtmoKB6vO2Y8OUaA==,type:str]
    adminEmail: ENC[AES256_GCM,data:+ZFo31Ffe+2j/v1RImD8,iv:V6wuawTvODluSFBnyUM0NCTEZ5bFrhdoWg4qvIC1Jdg=,tag:k1CcOk4o0n6YhOjYjpL39g==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbzE1RkFBV2xWQnh1ayt6
            ODNkMUFqOUVPVGdjV0J6Rnp0S3pGRktxUHk0Cm9GbllqdjVVYm00YTJEdEJTVjJ5
            S0JjZ3p2alJZVS93WnA0RWN2Q0NPeGMKLS0tIGt0MSt1MjhiamJpUWh4VTlkU21s
            Qm93SE5uYW5vNzVUS2phTFdISjdYR0kK7DfdqmR6Ll121NyZh+10MqnCdKSoCGP6
            MW01yGvLS1VvQYqGyW781WoSvxH8bcQRAHJx1CPMJ+1Jxr7fDeKSNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:56:19Z"
    mac: ENC[AES256_GCM,data:0Vjq5MCy1gvWcHYDjaGPwlcWS+87v5lQj0V/dATpo/ghaZ0mRP9QpBczDqWbhl/EJR+2wgQQcPyrhROmILrceUN/m336INQT6M4Eh6uJ61HA6VvyzFkjlqzuL5ieMRMqd/wrw2YfU6I+XjasgdrupUtU2fIOd2lL3Rny1o01Ar8=,iv:76Pgk1S4W+Xx+g0jkMyW69OlhJ44HI+0VdNXZGt9rFo=,tag:fPR4LB1ynTg3bgrSeISCyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
