apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: default
spec:
  selector: { app: paperless-web }
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: default
spec:
  selector: { app: paperless-postgres }
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  namespace: default
spec:
  selector: { app: paperless-redis }
  ports:
    - port: 6379
      targetPort: 6379
