apiVersion: ENC[AES256_GCM,data:RSc=,iv:zquTrcB7MBT61cWWY5RoZmWARjraoyUOXjH1ijVn/9E=,tag:0F2ib+b+H5luSnxp/GZACg==,type:str]
kind: ENC[AES256_GCM,data:taL4Szs5,iv:IhezNNj7353D10nSfPLGrPexq+hdFBMpNNB3DkCGYrk=,tag:aG+LA5pzos3pBBNmRibRbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uq96jew9wqNYrWPaZXSv,iv:fkFquRP2+b6YUJ0EoA+4vpjxYwzsqbUhi/4u+cPpLyU=,tag:njTdp20KSFaIbMnryHaieA==,type:str]
    namespace: ENC[AES256_GCM,data:Vo15hi70sbo6,iv:iu5kMBSuNZ4tsWNMtOCsQjbOP/qwhs3rJ2OkVnB+B+0=,tag:9xjTE/hfh+jIcp2tRdi1wA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:ynuSMOvcrZz8QlCYk3UUdvw=,iv:xVKIAwWSuE/M/fAWu7EuFPS/k8YjmTIyKAadIrNGgDw=,tag:tWfiiZ7iIpLHzh3FJV9KCw==,type:str]
    clientSecret: ENC[AES256_GCM,data:rX++Gdcxit6vt9nIGdYYg4+SaQE36LajZFzBpAgvv9pbHQprZHHK45M0m5DQazZxl+D6lHsFaj81k9q0qM/+ig==,iv:tfHT+aX+hESiKj9xB6w89lS0f7scSx/l5Uw/p4GHrbk=,tag:QYMmjxw5qb/6kEqFoiWmTA==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYVpzUEFIbXowYVptdDdi
            NE8wZjNJWGhwMHhJVlRDRnlCVTVVQWk2VFNBCks0YTFYUU1zc0tzZWF3Wi9nRjBm
            bnpjcDJXeGlGNlAycGlQZWZOd290SDAKLS0tIHoydlNad2RoMDcxaEwrUi9yVGtJ
            TmUzMHlKczJUQ0dxRDBSRFpxWk01STgK65vUoEuzFt0eCB1QrYIBZGCVoC65IS02
            fnUDvoPeVReRkJ6SCyp/+XF1pEsbWOU+gyZuodtHUwZcywKYuUYwSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T15:28:59Z"
    mac: ENC[AES256_GCM,data:GyXV/L6fR/w2X/uYOZ34/ovqbaZ5j8q7X14TAO///IB0cHs21ZUBIifrQT5zC7omviUNSuWuWoGvjxH/FyC5vUrQda8SrQMEZbWUvISU9bAHCnKJOZXYCdumnbjN630MiSCeSx2YAKAyqGrtdSIJDGiDeRzM7xIEeQqJtYZ8378=,iv:83PXuX+GsQ1VME7w38Lk1ZYkIKYQWOdjFCxzpsK77CQ=,tag:WPW+nf9dcsBqoSD/CJxqOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
