apiVersion: ENC[AES256_GCM,data:RSc=,iv:zquTrcB7MBT61cWWY5RoZmWARjraoyUOXjH1ijVn/9E=,tag:0F2ib+b+H5luSnxp/GZACg==,type:str]
kind: ENC[AES256_GCM,data:taL4Szs5,iv:IhezNNj7353D10nSfPLGrPexq+hdFBMpNNB3DkCGYrk=,tag:aG+LA5pzos3pBBNmRibRbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uq96jew9wqNYrWPaZXSv,iv:fkFquRP2+b6YUJ0EoA+4vpjxYwzsqbUhi/4u+cPpLyU=,tag:njTdp20KSFaIbMnryHaieA==,type:str]
    namespace: ENC[AES256_GCM,data:Vo15hi70sbo6,iv:iu5kMBSuNZ4tsWNMtOCsQjbOP/qwhs3rJ2OkVnB+B+0=,tag:9xjTE/hfh+jIcp2tRdi1wA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:Rst4pOEMMYdgmjvdpenl2M4=,iv:0g0GHcVGi4XMgqJeBw9SkYMOEw3W5nsOgEufVG5492c=,tag:a3ivVMzEoRr3UkL7BaMUGg==,type:str]
    clientSecret: ENC[AES256_GCM,data:ipmHLZKjsQqxm6FG0ybHjda+ooXZM0k84sK/8cL5amMhfw51sQBIrvQ+XSxYugPedxQFA/dUy2SPRU1wSQ2d,iv:+okdO9nSOtT2fielhNHL1JSm+Lv4N7Q0USNNp1xVgd4=,tag:yhoPsRhEEE7iQ8RI0lKG1Q==,type:str]
sops:
    age:
        - recipient: age15d84y5lsrjj5y3uhjpau8vd9d5aaz7c4hctgh9lx3qqnep8cf4sq5hvpge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYVpzUEFIbXowYVptdDdi
            NE8wZjNJWGhwMHhJVlRDRnlCVTVVQWk2VFNBCks0YTFYUU1zc0tzZWF3Wi9nRjBm
            bnpjcDJXeGlGNlAycGlQZWZOd290SDAKLS0tIHoydlNad2RoMDcxaEwrUi9yVGtJ
            TmUzMHlKczJUQ0dxRDBSRFpxWk01STgK65vUoEuzFt0eCB1QrYIBZGCVoC65IS02
            fnUDvoPeVReRkJ6SCyp/+XF1pEsbWOU+gyZuodtHUwZcywKYuUYwSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:56:19Z"
    mac: ENC[AES256_GCM,data:hfu0nI50i9fDkrjojjXOH9xNGAmRX8c+9xlxFnmR/CdRv95dDQpTGYB4uFv3hgyz0j9c3wlTVf96GXB4Ee+iy7F6i93ktgPC9O4g3WKx1/ZAZdMaKwcILJ43DoE1jftLO6MHmA43a15uPptp+aI93lqwJ3JHsZmWzpUk0EJeo3Q=,iv:CMuUlCGjMB0zS8HzRrkc5GvkGBa7FObk6nkSbBmljsU=,tag:8Wh7qoE56RfkC3P4VVCOwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
