apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: default
  labels:
    app: capacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capacitor
  template:
    metadata:
      labels:
        app: capacitor
    spec:
      serviceAccountName: capacitor
      containers:
        - name: capacitor
          image: ghcr.io/gimlet-io/capacitor-next:0.14.0
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet: { path: /, port: 9000 }
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet: { path: /, port: 9000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 500m, memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
